<?php
/**
 * Created by PhpStorm.
 * User: andrew
 * Date: 12/10/17
 * Time: 5:42 PM
 */

namespace Tests\Events;

use CQRS\DomainModels\User;
use CQRS\Events\UserCreatedCommand;
use Faker\Factory;
use Tests\TestCase;

class UserCreatedCommandTest extends TestCase
{

    private $user;

    public function setUp()
    {
        parent::setUp(); // TODO: Change the autogenerated stub

        $faker = Factory::create();

        $version = 1;
        $payload = [
            'name' => $faker->name,
            'email' => $faker->email,
            'password' => $faker->password
        ];

        $this->user = User::fromPayload($version, $payload);
    }

    public function testItHasValidData()
    {
        $command = new UserCreatedCommand($this->user);

        $this->assertNotNull($command->getName());
        $this->assertNotNull($command->getEmail());
        $this->assertNotNull($command->getPassword());
        $this->assertNotNull($command->getAggregateVersion());
    }
}
